apiVersion: v1
kind: Namespace
metadata:
  name: test-workload 
spec: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-workload-pvc 
  namespace: test-workload 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: managed-csi 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-workload-deploy 
  namespace: test-workload 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-workload-pod 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: test-workload-pod 
    spec:
      containers:
      - command:
        - sh
        - -c
        - |
          cd /data
          echo "starting sleep"
          while true
          do
          sleep 1
          done
        image: bullseie/test-workload:latest
        imagePullPolicy: IfNotPresent
        name: test-workload-container
        resources:
          requests:
            cpu: 1  
            memory: 1Gi
        volumeMounts:
        - mountPath: /data
          name: data      
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: test-workload-pvc
